name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Remove remote directory
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'rm -rf /usr/www/dapangmao/*'

      - name: Copy files to server
        run: scp -r -o StrictHostKeyChecking=no .next/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/usr/www/dapangmao

      - name: Copy package.json to server
        run: scp -o StrictHostKeyChecking=no package.json ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/usr/www/dapangmao

      - name: Install dependencies on server
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'cd /usr/www/dapangmao && npm install --production'

      - name: Restart server application
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'pm2 restart dapangmao'
