name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and build project
        run: |
          npm install
          npm run build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${SERVER_SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Compress build files
        run: tar -czf build.tar.gz -C .next .

      - name: Copy compressed file to server
        run: scp -o StrictHostKeyChecking=no build.tar.gz $SERVER_USERNAME@$SERVER_HOST:/usr/www/dapangmao

      - name: Deploy and restart application
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST << 'EOF'
            rm -rf /usr/www/dapangmao/{*,.*}
            tar -xzf /usr/www/dapangmao/build.tar.gz -C /usr/www/dapangmao
            rm /usr/www/dapangmao/build.tar.gz
            cd /usr/www/dapangmao
            pm2 restart dapangmao
          EOF
